### ISSUE TITLE
出现这个错误

### ISSUE THREAD

**Issue by chile-zhong** [ahasbini/Android-OpenCV#2]
Error:error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ahasbini** [comment]
Probably you didn't clone the entire repo with Git LFS, hence certain binaries for OpenCV 3.2.0 are missing. A more detailed message would be helpful. Also please check issue #1. You could checkout to tag 3.2.0 for the time being and try building again.
```
cd <path_to_project_root>/android-opencv
git checkout 3.2.0
```

**Comment by ahasbini** [comment]
Closing issue for no feedback for a while. Feel free to open it again.
