### ISSUE TITLE
i got this error when run app

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [ahasbini/Android-OpenCV#5]
Build command failed.
Error while executing process G:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\ndkrelatedprojecttemp\Android-OpenCV-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/jni/native-lib.cpp.o
[2/2] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so
FAILED: cmd.exe /C "cd . && G:\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android --gcc-toolchain=G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=G:/sdk/ndk-bundle/sysroot -fPIC -isystem G:/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot G:/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -LG:/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so @CMakeFiles/native-lib.rsp  && cd ."
G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld:F:/ndkrelatedprojecttemp/Android-OpenCV-master/opencv/src/sdk/native/libs/arm64-v8a/libopencv_calib3d.a: file format not recognized; treating as linker script
G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld:F:/ndkrelatedprojecttemp/Android-OpenCV-master/opencv/src/sdk/native/libs/arm64-v8a/libopencv_calib3d.a:1: syntax error
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by busylee999** [comment]
You got exactly same issue as me. Pls look [here](https://github.com/ahasbini/Android-OpenCV/issues/3#issuecomment-403640034)

**Comment by Jaymin-Bhadani** [comment]
no i cant fix it please help i got this error again

**Comment by Jaymin-Bhadani** [comment]
Build command failed.
Error while executing process G:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\ndkrelatedprojecttemp\Android-OpenCV-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so
FAILED: cmd.exe /C "cd . && G:\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android --gcc-toolchain=G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=G:/sdk/ndk-bundle/sysroot -fPIC -isystem G:/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot G:/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -LG:/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so @CMakeFiles/native-lib.rsp  && cd ."
G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld:F:/ndkrelatedprojecttemp/Android-OpenCV-master/opencv/src/sdk/native/libs/arm64-v8a/libopencv_calib3d.a: file format not recognized; treating as linker script
G:/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld:F:/ndkrelatedprojecttemp/Android-OpenCV-master/opencv/src/sdk/native/libs/arm64-v8a/libopencv_calib3d.a:1: syntax error
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by ahasbini** [comment]
Related to #1, please check for a possible solution there. Closing this issue and marking it as duplicate.
