### ISSUE TITLE
Native compilation failed [DetectionBasedTracker] in face-detection opencv sample

### ISSUE THREAD

**Issue by celsoolv** [ahasbini/Android-OpenCV#6]
I try to port sample from OpenCV sample pack for android. Sample is "face-detection"
Everything compiles now except of native code.
---------------------------------------------------------------------------------------------------
error
---------------------------------------------------------------------------------------------------

G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jni/DetectionBasedTracker_jni.cpp:68: error: undefined reference to 'cv::DetectionBasedTracker::Parameters::Parameters()'
E:/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2142: error: undefined reference to 'cv::DetectionBasedTracker::DetectionBasedTracker(cv::Ptr<cv::DetectionBasedTracker::IDetector>, cv::Ptr<cv::DetectionBasedTracker::IDetector>, cv::DetectionBasedTracker::Parameters const&)'
E:/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2120: error: undefined reference to 'cv::DetectionBasedTracker::~DetectionBasedTracker()'
E:/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2142: error: undefined reference to 'cv::CascadeClassifier::CascadeClassifier(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
E:/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:3696: error: undefined reference to 'cv::CascadeClassifier::~CascadeClassifier()'
E:/Android/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2120: error: undefined reference to 'cv::CascadeClassifier::~CascadeClassifier()'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jni/DetectionBasedTracker_jni.cpp:39: error: undefined reference to 'cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::__ndk1::vector<cv::Rect_<int>, std::__ndk1::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::open(char const*, int, char const*): error: undefined reference to 'gzopen'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::gets(char*, int): error: undefined reference to 'gzgets'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::puts(char const*): error: undefined reference to 'gzputs'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::eof(): error: undefined reference to 'gzeof'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::closeFile(): error: undefined reference to 'gzclose'
G:/Projetos/Software/Skin/OpenCvPrj/face-detection/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::rewind(): error: undefined reference to 'gzrewind'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

---------------------------------------------------------------------------------------------------
code
---------------------------------------------------------------------------------------------------
#include <DetectionBasedTracker_jni.h>
//#include <opencv2/objdetect/detection_Based_Tracker.hpp>
#include <opencv2/core.hpp>
#include <opencv2/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/objdetect.hpp>

#include <string>
#include <vector>

#include <android/log.h>

#define LOG_TAG "FaceDetection/DetectionBasedTracker"
#define LOGD(...) ((void)__android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__))

using namespace std;
using namespace cv;

inline void vector_Rect_to_Mat(vector<Rect>& v_rect, Mat& mat)
{
    mat = Mat(v_rect, true);
}

class CascadeDetectorAdapter: public DetectionBasedTracker::IDetector
{
public:
    CascadeDetectorAdapter(cv::Ptr<cv::CascadeClassifier> detector):
            IDetector(),
            Detector(detector)
    {
        LOGD("CascadeDetectorAdapter::Detect::Detect");
        CV_Assert(detector);
    }

    void detect(const cv::Mat &Image, std::vector<cv::Rect> &objects)
    {
        LOGD("CascadeDetectorAdapter::Detect: begin");
        LOGD("CascadeDetectorAdapter::Detect: scaleFactor=%.2f, minNeighbours=%d, minObjSize=(%dx%d), maxObjSize=(%dx%d)", scaleFactor, minNeighbours, minObjSize.width, minObjSize.height, maxObjSize.width, maxObjSize.height);
        Detector->detectMultiScale(Image, objects, scaleFactor, minNeighbours, 0, minObjSize, maxObjSize);
        LOGD("CascadeDetectorAdapter::Detect: end");
    }

    virtual ~CascadeDetectorAdapter()
    {
        LOGD("CascadeDetectorAdapter::Detect::~Detect");
    }

private:
    CascadeDetectorAdapter();
    cv::Ptr<cv::CascadeClassifier> Detector;
};

struct DetectorAgregator
{
    cv::Ptr<CascadeDetectorAdapter> mainDetector;
    cv::Ptr<CascadeDetectorAdapter> trackingDetector;

    cv::Ptr<DetectionBasedTracker> tracker;
    DetectorAgregator(cv::Ptr<CascadeDetectorAdapter>& _mainDetector, cv::Ptr<CascadeDetectorAdapter>& _trackingDetector):
            mainDetector(_mainDetector),
            trackingDetector(_trackingDetector)
    {

        CV_Assert(_mainDetector);
        CV_Assert(_trackingDetector);

        DetectionBasedTracker::Parameters DetectorParams;
        tracker = makePtr<DetectionBasedTracker>(mainDetector, trackingDetector, DetectorParams);
    }
};

JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeCreateObject
(JNIEnv * jenv, jclass, jstring jFileName, jint faceSize)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeCreateObject enter");
    const char* jnamestr = jenv->GetStringUTFChars(jFileName, NULL);
    string stdFileName(jnamestr);
    jlong result = 0;

    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeCreateObject");

    try
    {
        cv::Ptr<CascadeDetectorAdapter> mainDetector = makePtr<CascadeDetectorAdapter>(
            makePtr<CascadeClassifier>(stdFileName));
        cv::Ptr<CascadeDetectorAdapter> trackingDetector = makePtr<CascadeDetectorAdapter>(
            makePtr<CascadeClassifier>(stdFileName));
        result = (jlong)new DetectorAgregator(mainDetector, trackingDetector);
        if (faceSize > 0)
        {
            mainDetector->setMinObjectSize(Size(faceSize, faceSize));
            //trackingDetector->setMinObjectSize(Size(faceSize, faceSize));
        }
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeCreateObject caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeCreateObject caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code of DetectionBasedTracker.nativeCreateObject()");
        return 0;
    }

    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeCreateObject exit");
    return result;
}

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDestroyObject
(JNIEnv * jenv, jclass, jlong thiz)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDestroyObject");

    try
    {
        if(thiz != 0)
        {
            ((DetectorAgregator*)thiz)->tracker->stop();
            delete (DetectorAgregator*)thiz;
        }
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeestroyObject caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeDestroyObject caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code of DetectionBasedTracker.nativeDestroyObject()");
    }
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDestroyObject exit");
}

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStart
(JNIEnv * jenv, jclass, jlong thiz)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStart");

    try
    {
        ((DetectorAgregator*)thiz)->tracker->run();
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeStart caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeStart caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code of DetectionBasedTracker.nativeStart()");
    }
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStart exit");
}

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStop
(JNIEnv * jenv, jclass, jlong thiz)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStop");

    try
    {
        ((DetectorAgregator*)thiz)->tracker->stop();
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeStop caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeStop caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code of DetectionBasedTracker.nativeStop()");
    }
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeStop exit");
}

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetFaceSize
(JNIEnv * jenv, jclass, jlong thiz, jint faceSize)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetFaceSize -- BEGIN");

    try
    {
        if (faceSize > 0)
        {
            ((DetectorAgregator*)thiz)->mainDetector->setMinObjectSize(Size(faceSize, faceSize));
            //((DetectorAgregator*)thiz)->trackingDetector->setMinObjectSize(Size(faceSize, faceSize));
        }
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeStop caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeSetFaceSize caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code of DetectionBasedTracker.nativeSetFaceSize()");
    }
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeSetFaceSize -- END");
}

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDetect
(JNIEnv * jenv, jclass, jlong thiz, jlong imageGray, jlong faces)
{
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDetect");

    try
    {
        vector<Rect> RectFaces;
        ((DetectorAgregator*)thiz)->tracker->process(*((Mat*)imageGray));
        ((DetectorAgregator*)thiz)->tracker->getObjects(RectFaces);
        *((Mat*)faces) = Mat(RectFaces, true);
    }
    catch(const cv::Exception& e)
    {
        LOGD("nativeCreateObject caught cv::Exception: %s", e.what());
        jclass je = jenv->FindClass("org/opencv/core/CvException");
        if(!je)
            je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, e.what());
    }
    catch (...)
    {
        LOGD("nativeDetect caught unknown exception");
        jclass je = jenv->FindClass("java/lang/Exception");
        jenv->ThrowNew(je, "Unknown exception in JNI code DetectionBasedTracker.nativeDetect()");
    }
    LOGD("Java_org_opencv_samples_facedetect_DetectionBasedTracker_nativeDetect END");
}

**Comment by ahasbini** [comment]
Probably related to #1, please check for a possible solution there. Closing this issue and marking it as duplicate.

**Comment by kokeras** [comment]
Just got the same error. Trying OpenCV 4.4.0 with precompiled libraries available for Andriud. Can't build face detection example coming along with library. Thread probably related by @ahasbini seems to have nothing to do with this issue. Any thoughts on this? Lack of documentation to guess by myself, but seems that a zlib precompiled library is missing among all armeabi-v7a set of them into 4.4.0 package. I thik that as source code on GIT for OpenCV for [persistence.cpp](https://github.com/opencv/opencv/blob/master/modules/core/src/persistence.cpp) shows a conditional about it:

#if USE_ZLIB
                char mode[] = { write_mode ? 'w' : 'r', 'b', compression ? compression : '3', '\0' };
                gzfile = gzopen(filename.c_str(), mode);
                if( !gzfile )
                    return false;
#else
                CV_Error(CV_StsNotImplemented, "There is no compressed file storage support in this configuration");
#endif

Here is the build output for my intent:

Build command failed.
Error while executing process C:\Users\Paco\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C C:\Users\Paco\StudioProjects\TestOpenCVNative\app\.cxx\cmake\debug\armeabi-v7a native-lib}
ninja: Entering directory `C:\Users\Paco\StudioProjects\TestOpenCVNative\app\.cxx\cmake\debug\armeabi-v7a'
[1/1] Linking CXX shared library C:\Users\Paco\StudioProjects\TestOpenCVNative\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so
FAILED: C:/Users/Paco/StudioProjects/TestOpenCVNative/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so 
cmd.exe /C "cd . && C:\Users\Paco\AppData\Local\Android\Sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --gcc-toolchain=C:/Users/Paco/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/Paco/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -std=gnu++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libnative-lib.so -o C:\Users\Paco\StudioProjects\TestOpenCVNative\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so CMakeFiles/native-lib.dir/DetectionBasedTracker_jni.cpp.o -LC:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a -llog C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libtbb.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libcpufeatures.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_imgproc.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_videoio.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_highgui.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_video.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_calib3d.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_features2d.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_objdetect.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_dnn.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_ml.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_flann.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_photo.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_stitching.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libIlmImf.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libittnotify.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibjasper.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibjpeg-turbo.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibpng.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibprotobuf.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibtiff.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/liblibwebp.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_gapi.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_imgcodecs.a -lopencv_java4 C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libquirc.a C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libtegra_hal.a -latomic -lm && cd ."
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::open(char const*, int, char const*): error: undefined reference to 'gzopen'
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::getsFromFile(char*, int): error: undefined reference to 'gzgets'
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::puts(char const*): error: undefined reference to 'gzputs'
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::eof(): error: undefined reference to 'gzeof'
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::closeFile(): error: undefined reference to 'gzclose'
C:/Users/Paco/StudioProjects/TestOpenCVNative/app/src/main/jniLibs/armeabi-v7a/libopencv_core.a(persistence.cpp.o):persistence.cpp:function cv::FileStorage::Impl::rewind(): error: undefined reference to 'gzrewind'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
